from __future__ import annotations

def _dimensions(reliability: int, feedback: int, quality: int, capacity: int, tasks: int) -> list[dict]:
    return [
        {"code": "RELIABILITY", "label": "可靠性", "score": reliability, "minimum": 18, "weight": 30},
        {"code": "USER_FEEDBACK", "label": "用户反馈", "score": feedback, "minimum": 6, "weight": 20},
        {"code": "CLASS_QUALITY", "label": "课堂质量", "score": quality, "minimum": 15, "weight": 25},
        {"code": "CAPACITY", "label": "产能", "score": capacity, "minimum": 8, "weight": 15},
        {"code": "NEW_TEACHER_TASK", "label": "新师任务", "score": tasks, "minimum": 8, "weight": 10},
    ]


def seed_teachers() -> list[dict]:
    return [
        {
            "teacher_id": "T-1001",
            "name": "Maria Santos",
            "avatar": "MS",
            "country": "Philippines",
            "timezone": "Asia/Manila",
            "camp_day": 2,
            "lessons_completed": 0,
            "total_score": 21,
            "graduation_threshold": 80,
            "graduation_state": "IN_PROGRESS",
            "dimensions": _dimensions(0, 0, 10, 6, 5),
            "gates": [{"code": "POLICY", "status": "PASSED"}, {"code": "DEVICE", "status": "PASSED"}],
            "signals": [
                {
                    "signal_id": "SIG-ABSENT-1001",
                    "code": "FIRST_LESSON_PHYSICAL_ABSENCE",
                    "status": "VALID",
                    "severity": "P0",
                    "occurred_at": "2026-07-16T01:00:00Z",
                    "route": "DIRECT",
                    "evidence_refs": ["LESSON-L-1001:PRESENCE-CONFIRMED"],
                }
            ],
            "lesson_facts": [
                {
                    "lesson_id": "L-1001",
                    "appoint_id": "A-1001",
                    "is_first_lesson_mock": True,
                    "scheduled_start_at": "2026-07-16T01:00:00Z",
                    "lesson_status": "ENDED",
                    "teacher_presence": "ABSENT",
                    "evidence_status": "CONFIRMED",
                    "evidence_source": "ovs_dw_teacher_fact_1v1_buy_performance (MOCK)",
                    "data_mode": "MOCK",
                }
            ],
            "lesson_dimension_scores": [
                {
                    "lesson_id": "L-1001",
                    "dimension": "RELIABILITY",
                    "score": 0,
                    "evidence_status": "CONFIRMED",
                    "reason_code": "REDLINE_RECORDED_NO_DEDUCTION",
                },
                {
                    "lesson_id": "L-1001",
                    "dimension": "USER_FEEDBACK",
                    "score": 0,
                    "evidence_status": "NO_EVIDENCE",
                    "reason_code": "NO_SETTLEABLE_EVIDENCE",
                },
                {
                    "lesson_id": "L-1001",
                    "dimension": "CLASS_QUALITY",
                    "score": 0,
                    "evidence_status": "NOT_APPLICABLE",
                    "reason_code": "TEACHER_PHYSICALLY_ABSENT",
                },
            ],
            "score_entries": [
                {
                    "score_entry_id": "SCORE-L-1001-RELIABILITY",
                    "lesson_id": "L-1001",
                    "dimension": "RELIABILITY",
                    "delta": 0,
                    "reason_code": "REDLINE_RECORDED_NO_DEDUCTION",
                    "evidence_ref": "LESSON-L-1001:PRESENCE-CONFIRMED",
                    "rule_version": 1,
                }
            ],
            "risk_tags": ["首课缺席", "可靠性低于最低线"],
            "next_best_action": "确认是否继续授课，并由运营评估后续排课",
            "updated_at": "2026-07-16T09:00:00Z",
        },
        {
            "teacher_id": "T-1002",
            "name": "Ana Cruz",
            "avatar": "AC",
            "country": "Philippines",
            "timezone": "Asia/Manila",
            "camp_day": 4,
            "lessons_completed": 6,
            "total_score": 57,
            "graduation_threshold": 80,
            "graduation_state": "IN_PROGRESS",
            "dimensions": _dimensions(20, 8, 11, 10, 8),
            "gates": [{"code": "POLICY", "status": "PASSED"}, {"code": "DEVICE", "status": "RECHECK_REQUIRED"}],
            "signals": [
                {
                    "signal_id": "SIG-NET-1002",
                    "code": "NETWORK_RISK",
                    "status": "VALID",
                    "severity": "P1",
                    "occurred_at": "2026-07-16T02:00:00Z",
                    "evidence_refs": ["LESSON-L-1002:NETWORK-QUALITY-CONFIRMED"],
                },
                {
                    "signal_id": "SIG-PREP-1002",
                    "code": "LESSON_PREP_RISK",
                    "status": "VALID",
                    "severity": "P2",
                    "occurred_at": "2026-07-16T02:05:00Z",
                    "evidence_refs": ["LESSON-L-1002:PREPARATION-RISK-CONFIRMED"],
                },
                {
                    "signal_id": "SIG-CAPACITY-1002",
                    "code": "PEAK_SLOTS_BELOW_TARGET",
                    "status": "VALID",
                    "severity": "P3",
                    "occurred_at": "2026-07-16T02:10:00Z",
                    "evidence_refs": ["CAPACITY-T1002:ROLLING-7D-PEAK-SLOTS"],
                },
            ],
            "risk_tags": ["网络波动", "课堂质量低于最低线"],
            "next_best_action": "完成设备与网络重检",
            "updated_at": "2026-07-16T09:05:00Z",
        },
        {
            "teacher_id": "T-1003",
            "name": "John Reyes",
            "avatar": "JR",
            "country": "Philippines",
            "timezone": "Asia/Manila",
            "camp_day": 1,
            "lessons_completed": 0,
            "total_score": 40,
            "graduation_threshold": 80,
            "graduation_state": "IN_PROGRESS",
            "dimensions": _dimensions(18, 0, 15, 4, 3),
            "gates": [{"code": "POLICY", "status": "PENDING"}, {"code": "DEVICE", "status": "PASSED"}],
            "signals": [
                {
                    "signal_id": "SIG-INTRO-1003",
                    "code": "SELF_INTRO_MISSING",
                    "status": "VALID",
                    "severity": "P1",
                    "occurred_at": "2026-07-16T03:00:00Z",
                    "evidence_refs": ["CAMP-T1003:SELF-INTRO-MISSING"],
                },
                {
                    "signal_id": "SIG-POLICY-1003",
                    "code": "POLICY_QUIZ_REQUIRED",
                    "status": "VALID",
                    "severity": "P1",
                    "occurred_at": "2026-07-16T03:00:00Z",
                    "evidence_refs": ["CAMP-T1003:POLICY-QUIZ-PENDING"],
                },
            ],
            "risk_tags": ["必修任务未完成", "尚无付费课样本"],
            "next_best_action": "完成 Self-intro 上传与规则学习",
            "updated_at": "2026-07-16T09:10:00Z",
        },
        {
            "teacher_id": "T-1004",
            "name": "Liza Gomez",
            "avatar": "LG",
            "country": "Philippines",
            "timezone": "Asia/Manila",
            "camp_day": 9,
            "lessons_completed": 18,
            "total_score": 86,
            "graduation_threshold": 80,
            "graduation_state": "IN_PROGRESS",
            "dimensions": _dimensions(26, 14, 22, 14, 10),
            "gates": [{"code": "POLICY", "status": "PASSED"}, {"code": "DEVICE", "status": "PASSED"}],
            "signals": [],
            "risk_tags": ["尚未达到出营标准"],
            "next_best_action": "继续积累有效课程与用户反馈",
            "updated_at": "2026-07-16T09:15:00Z",
        },
    ]
