"""initial PostgreSQL persistence foundation

Revision ID: 27db1e431977
Revises:
Create Date: 2026-07-17 11:12:16.724750
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '27db1e431977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('plan_key', sa.String(length=512), nullable=False),
    sa.Column('route', sa.String(length=24), nullable=False),
    sa.Column('planner', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('selected_template_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('plan_key')
    )
    op.create_index(op.f('ix_agent_decisions_teacher_id'), 'agent_decisions', ['teacher_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_task_id'), 'audit_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_audit_events_teacher_id'), 'audit_events', ['teacher_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('scope', 'idempotency_key')
    )
    op.create_table('outbound_outputs',
    sa.Column('output_id', sa.String(length=128), nullable=False),
    sa.Column('output_type', sa.String(length=32), nullable=False),
    sa.Column('display_type', sa.String(length=40), nullable=False),
    sa.Column('delivery_kind', sa.String(length=40), nullable=True),
    sa.Column('audience_type', sa.String(length=32), nullable=False),
    sa.Column('recipient_id', sa.String(length=128), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('output_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_outbound_output_idempotency')
    )
    op.create_index(op.f('ix_outbound_outputs_case_id'), 'outbound_outputs', ['case_id'], unique=False)
    op.create_index(op.f('ix_outbound_outputs_display_type'), 'outbound_outputs', ['display_type'], unique=False)
    op.create_index(op.f('ix_outbound_outputs_output_type'), 'outbound_outputs', ['output_type'], unique=False)
    op.create_index(op.f('ix_outbound_outputs_status'), 'outbound_outputs', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_outputs_task_id'), 'outbound_outputs', ['task_id'], unique=False)
    op.create_index(op.f('ix_outbound_outputs_teacher_id'), 'outbound_outputs', ['teacher_id'], unique=False)
    op.create_index('ix_outputs_type_status_teacher', 'outbound_outputs', ['output_type', 'status', 'teacher_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=48), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('provider_calls',
    sa.Column('provider_call_id', sa.String(length=128), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('call_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_call_id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_provider_calls_task_id'), 'provider_calls', ['task_id'], unique=False)
    op.create_table('task_templates',
    sa.Column('row_id', sa.String(length=160), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.String(length=24), nullable=False),
    sa.Column('output_type', sa.String(length=32), nullable=False),
    sa.Column('task_category', sa.String(length=48), nullable=False),
    sa.Column('audience', sa.String(length=24), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('completion_method', sa.String(length=32), nullable=False),
    sa.Column('verification_mode', sa.String(length=32), nullable=False),
    sa.Column('action_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('template_id', 'template_version', name='uq_task_template_version')
    )
    op.create_index(op.f('ix_task_templates_template_id'), 'task_templates', ['template_id'], unique=False)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('camp_day', sa.Integer(), nullable=False),
    sa.Column('graduation_state', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('graduation_threshold', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('camp_enrollment_id')
    )
    op.create_table('lesson_facts',
    sa.Column('lesson_id', sa.String(length=128), nullable=False),
    sa.Column('source_appoint_id', sa.String(length=128), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lesson_lifecycle_status', sa.String(length=48), nullable=False),
    sa.Column('valid_for_scoring', sa.Boolean(), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_index(op.f('ix_lesson_facts_camp_enrollment_id'), 'lesson_facts', ['camp_enrollment_id'], unique=False)
    op.create_index(op.f('ix_lesson_facts_teacher_id'), 'lesson_facts', ['teacher_id'], unique=False)
    op.create_table('ops_cases',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_reason', sa.String(length=64), nullable=True),
    sa.Column('external_action_status', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_ops_cases_case_type'), 'ops_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_ops_cases_status'), 'ops_cases', ['status'], unique=False)
    op.create_index(op.f('ix_ops_cases_task_id'), 'ops_cases', ['task_id'], unique=False)
    op.create_index(op.f('ix_ops_cases_teacher_id'), 'ops_cases', ['teacher_id'], unique=False)
    op.create_table('score_accounts',
    sa.Column('account_id', sa.String(length=160), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('minimum_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score_rule_version', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('teacher_id', 'dimension', name='uq_score_account_teacher_dimension')
    )
    op.create_index(op.f('ix_score_accounts_camp_enrollment_id'), 'score_accounts', ['camp_enrollment_id'], unique=False)
    op.create_index(op.f('ix_score_accounts_teacher_id'), 'score_accounts', ['teacher_id'], unique=False)
    op.create_table('score_entries',
    sa.Column('score_entry_id', sa.String(length=128), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('lesson_id', sa.String(length=128), nullable=True),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('delta_score', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('score_rule_version', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversal_of_score_entry_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('score_entry_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_score_entries_camp_enrollment_id'), 'score_entries', ['camp_enrollment_id'], unique=False)
    op.create_index(op.f('ix_score_entries_lesson_id'), 'score_entries', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_score_entries_teacher_id'), 'score_entries', ['teacher_id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('obligation_id', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('assignment_revision', sa.Integer(), nullable=False),
    sa.Column('execution_contract_version', sa.Integer(), nullable=False),
    sa.Column('assignment_status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('display_rank', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_assignments_assignment_status'), 'task_assignments', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_task_assignments_camp_enrollment_id'), 'task_assignments', ['camp_enrollment_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_obligation_id'), 'task_assignments', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_priority'), 'task_assignments', ['priority'], unique=False)
    op.create_index(op.f('ix_task_assignments_teacher_id'), 'task_assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_template_id'), 'task_assignments', ['template_id'], unique=False)
    op.create_table('lesson_dimension_scores',
    sa.Column('score_state_id', sa.String(length=256), nullable=False),
    sa.Column('camp_enrollment_id', sa.String(length=96), nullable=False),
    sa.Column('lesson_id', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_coverage', sa.String(length=32), nullable=True),
    sa.Column('score_rule_version', sa.String(length=64), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('score_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_score_entry_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_facts.lesson_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('score_state_id'),
    sa.UniqueConstraint('camp_enrollment_id', 'lesson_id', 'dimension', name='uq_lesson_dimension_state')
    )
    op.create_index(op.f('ix_lesson_dimension_scores_camp_enrollment_id'), 'lesson_dimension_scores', ['camp_enrollment_id'], unique=False)
    op.create_index(op.f('ix_lesson_dimension_scores_lesson_id'), 'lesson_dimension_scores', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_dimension_scores_teacher_id'), 'lesson_dimension_scores', ['teacher_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_assignments.task_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_teacher_id'), 'notifications', ['teacher_id'], unique=False)
    op.create_table('ops_decisions',
    sa.Column('decision_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['ops_cases.case_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_ops_decisions_case_id'), 'ops_decisions', ['case_id'], unique=False)
    op.create_table('task_executions',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_status', sa.String(length=32), nullable=False),
    sa.Column('verification_result', sa.String(length=32), nullable=True),
    sa.Column('runtime_sequence', sa.Integer(), nullable=False),
    sa.Column('due_status', sa.String(length=16), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_assignments.task_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_executions_runtime_status'), 'task_executions', ['runtime_status'], unique=False)
    op.create_table('task_runtime_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('execution_contract_version', sa.Integer(), nullable=False),
    sa.Column('runtime_sequence', sa.Integer(), nullable=False),
    sa.Column('runtime_event_code', sa.String(length=48), nullable=False),
    sa.Column('runtime_status', sa.String(length=32), nullable=False),
    sa.Column('verification_result', sa.String(length=32), nullable=True),
    sa.Column('provider_event_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_assignments.task_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('task_id', 'runtime_sequence', name='uq_task_runtime_sequence')
    )
    op.create_index(op.f('ix_task_runtime_events_task_id'), 'task_runtime_events', ['task_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('notification_event_id', sa.String(length=128), nullable=False),
    sa.Column('notification_id', sa.String(length=128), nullable=False),
    sa.Column('delivery_status', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('notification_event_id')
    )
    op.create_index(op.f('ix_notification_events_notification_id'), 'notification_events', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_events_notification_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_task_runtime_events_task_id'), table_name='task_runtime_events')
    op.drop_table('task_runtime_events')
    op.drop_index(op.f('ix_task_executions_runtime_status'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_ops_decisions_case_id'), table_name='ops_decisions')
    op.drop_table('ops_decisions')
    op.drop_index(op.f('ix_notifications_teacher_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lesson_dimension_scores_teacher_id'), table_name='lesson_dimension_scores')
    op.drop_index(op.f('ix_lesson_dimension_scores_lesson_id'), table_name='lesson_dimension_scores')
    op.drop_index(op.f('ix_lesson_dimension_scores_camp_enrollment_id'), table_name='lesson_dimension_scores')
    op.drop_table('lesson_dimension_scores')
    op.drop_index(op.f('ix_task_assignments_template_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_teacher_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_priority'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_obligation_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_camp_enrollment_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_assignment_status'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_score_entries_teacher_id'), table_name='score_entries')
    op.drop_index(op.f('ix_score_entries_lesson_id'), table_name='score_entries')
    op.drop_index(op.f('ix_score_entries_camp_enrollment_id'), table_name='score_entries')
    op.drop_table('score_entries')
    op.drop_index(op.f('ix_score_accounts_teacher_id'), table_name='score_accounts')
    op.drop_index(op.f('ix_score_accounts_camp_enrollment_id'), table_name='score_accounts')
    op.drop_table('score_accounts')
    op.drop_index(op.f('ix_ops_cases_teacher_id'), table_name='ops_cases')
    op.drop_index(op.f('ix_ops_cases_task_id'), table_name='ops_cases')
    op.drop_index(op.f('ix_ops_cases_status'), table_name='ops_cases')
    op.drop_index(op.f('ix_ops_cases_case_type'), table_name='ops_cases')
    op.drop_table('ops_cases')
    op.drop_index(op.f('ix_lesson_facts_teacher_id'), table_name='lesson_facts')
    op.drop_index(op.f('ix_lesson_facts_camp_enrollment_id'), table_name='lesson_facts')
    op.drop_table('lesson_facts')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_task_templates_template_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_provider_calls_task_id'), table_name='provider_calls')
    op.drop_table('provider_calls')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_outputs_type_status_teacher', table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_teacher_id'), table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_task_id'), table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_status'), table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_output_type'), table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_display_type'), table_name='outbound_outputs')
    op.drop_index(op.f('ix_outbound_outputs_case_id'), table_name='outbound_outputs')
    op.drop_table('outbound_outputs')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_audit_events_teacher_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_task_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_decisions_teacher_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
